version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci

  release:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npx semantic-release

  'basic test':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/basic

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - cypress/install
      - 'basic test':
          requires:
            - cypress/install
      - release:
          requires:
            - build
            - 'basic test'
          filters:
            branches:
              only:
                - master
                - beta
